export const addItemFormTranslations = {
  en: {
    // Toast Messages
    toast: {
      noImagesTitle: "No images",
      noImagesDesc: "Please add at least one image of your item",
      uploadInProgressTitle: "Upload in progress",
      uploadInProgressDesc: "Please wait until all images finish uploading",
      errorTitle: "Error",
      errorDesc: "Failed to generate item data. Please try again.",
    },
    
    // Section Headers
    sections: {
      uploadImages: "Upload Images",
      optionalDetails: "Optional Details",
      helperText: "You can optionally provide a title and expected price. All other details will be automatically generated by AI from your images.",
    },
    
    // Form Labels (simplified - only title and expected_price)
    labels: {
      title: "Title",
      expectedPrice: "Expected Price",
    },
    
    // Placeholders
    placeholders: {
      title: "Leave empty for AI to generate",
      expectedPrice: "Your price expectation (e.g., 50.00)",
    },
    
    // Buttons
    buttons: {
      generating: "Analyzing images with AI...",
      continue: "Continue",
    },
  },
  
  pl: {
    // Powiadomienia Toast
    toast: {
      noImagesTitle: "Brak zdjęć",
      noImagesDesc: "Dodaj co najmniej jedno zdjęcie przedmiotu",
      uploadInProgressTitle: "Trwa przesyłanie",
      uploadInProgressDesc: "Poczekaj, aż wszystkie zdjęcia zostaną przesłane",
      errorTitle: "Błąd",
      errorDesc: "Nie udało się wygenerować danych przedmiotu. Spróbuj ponownie.",
    },
    
    // Nagłówki sekcji
    sections: {
      uploadImages: "Prześlij zdjęcia",
      optionalDetails: "Opcjonalne szczegóły",
      helperText: "Opcjonalnie możesz podać tytuł i oczekiwaną cenę. Pozostałe szczegóły AI wygeneruje na podstawie zdjęć.",
    },
    
    // Etykiety formularza (uproszczone - tylko tytuł i oczekiwana cena)
    labels: {
      title: "Tytuł",
      expectedPrice: "Oczekiwana cena",
    },
    
    // Placeholdery
    placeholders: {
      title: "Zostaw puste, aby AI wygenerowało tytuł",
      expectedPrice: "Podaj cenę (np. 50,00)",
    },
    
    // Przyciski
    buttons: {
      generating: "Analiza zdjęć przez AI...",
      continue: "Kontynuuj",
    },
  },
};

export type AddItemFormTranslations = typeof addItemFormTranslations.en;
