export const addItemFormTranslations = {
  en: {
    // Toast Messages
    toast: {
      noImagesTitle: "No images",
      noImagesDesc: "Please add at least one image of your item",
      uploadInProgressTitle: "Upload in progress",
      uploadInProgressDesc: "Please wait until all images finish uploading",
      errorTitle: "Error",
      errorDesc: "We couldn't analyze this image right now. Please try again later or contact support if the problem continues.",
      contactSupport: "Contact support",
    },
    
    // Section Headers
    sections: {
      uploadImages: "Add photos",
      optionalDetails: "Additional information",
      helperText: "You can optionally provide a title and expected price. All other details will be automatically generated by AI from your images.",
    },
    
    // Form Labels (simplified - only title and expected_price)
    labels: {
      title: "Title",
      expectedPrice: "Expected Price",
      currency: "Currency",
      optional: "optional",
    },
    
    // Placeholders
    placeholders: {
      title: "Leave empty for AI to generate",
      expectedPrice: "Your price expectation in {currency} (e.g., 50.00)",
    },
    
    // Buttons
    buttons: {
      generating: "Analyzing images with AI...",
      continue: "Continue",
      noImageCredits: "No image credits",
    },

    imageEnhancement: {
      label: "Create an AI-enhanced product photo",
      description: "Create a separate version with improved background and lighting. Your original photo stays unchanged.",
      oneCredit: "1 credit",
      free: "Free",
      unavailableTitle: "No AI image credits left",
      unavailableDescription: (remaining: number) =>
        `You have ${remaining} AI image enhancements left. Compare plans or buy an image-credit add-on in Settings to continue.`,
    },
  },
  
  pl: {
    // Powiadomienia Toast
    toast: {
      noImagesTitle: "Brak zdjęć",
      noImagesDesc: "Dodaj co najmniej jedno zdjęcie przedmiotu",
      uploadInProgressTitle: "Trwa przesyłanie",
      uploadInProgressDesc: "Poczekaj, aż wszystkie zdjęcia zostaną przesłane",
      errorTitle: "Błąd",
      errorDesc: "Nie udało się teraz przeanalizować tego zdjęcia. Spróbuj ponownie później lub skontaktuj się ze wsparciem, jeśli problem będzie się powtarzał.",
      contactSupport: "Kontakt ze wsparciem",
    },
    
    // Nagłówki sekcji
    sections: {
      uploadImages: "Dodaj zdjęcia",
      optionalDetails: "Dodatkowe informacje",
      helperText: "Opcjonalnie możesz podać tytuł i oczekiwaną cenę. Pozostałe szczegóły AI wygeneruje na podstawie zdjęć.",
    },
    
    // Etykiety formularza (uproszczone - tylko tytuł i oczekiwana cena)
    labels: {
      title: "Tytuł",
      expectedPrice: "Oczekiwana cena",
      currency: "Waluta",
      optional: "opcjonalnie",
    },
    
    // Placeholdery
    placeholders: {
      title: "Zostaw puste, aby AI wygenerowało tytuł",
      expectedPrice: "Podaj cenę w {currency} (np. 50,00)",
    },
    
    // Przyciski
    buttons: {
      generating: "Analiza zdjęć przez AI...",
      continue: "Kontynuuj",
      noImageCredits: "Brak kredytów na zdjęcia",
    },

    imageEnhancement: {
      label: "Utwórz ulepszoną wersję zdjęcia przez AI",
      description: "Utwórz osobną wersję z poprawionym tłem i oświetleniem. Oryginalne zdjęcie pozostanie bez zmian.",
      oneCredit: "1 kredyt",
      free: "Bezpłatnie",
      unavailableTitle: "Brak kredytów na ulepszenie zdjęcia",
      unavailableDescription: (remaining: number) =>
        `Pozostało Ci ${remaining} ulepszeń zdjęć przez AI. Porównaj plany lub kup dodatkowe kredyty na zdjęcia w Ustawieniach, aby kontynuować.`,
    },
  },
};

export type AddItemFormTranslations = typeof addItemFormTranslations.en;
